/*
 * This code is part of the ThornSec project.
 *
 * To learn more, please head to its GitHub repo: @privacyint
 *
 * Pull requests encouraged.
 */
package core.model.machine.configuration;

import java.io.File;
import java.util.Optional;
import org.apache.commons.io.FilenameUtils;
import core.data.machine.configuration.DiskData;
import core.data.machine.configuration.DiskData.Format;
import core.data.machine.configuration.DiskData.Medium;
import core.exception.AThornSecException;
import core.exception.data.machine.InvalidDiskSizeException;
import core.model.AModel;
import core.model.network.NetworkModel;

public class DiskModel extends AModel {
	private Medium medium;
	private Format format;
	private File filename;
	private Integer size;
	private File diffParent;
	private String comment;

	public DiskModel(String label, Medium medium, Format format, File filename, Integer size, File diffParent, String comment, NetworkModel networkModel) throws InvalidDiskSizeException {
		super(new DiskData(label), networkModel);
		this.setLabel(label);
		setMedium(medium);
		setFormat(format);
		setFilename(filename);
		setSize(size);
		setDiffParent(diffParent);
		setComment(comment);
	}
	
	public DiskModel(DiskData myData, NetworkModel networkModel) throws InvalidDiskSizeException {
		this(myData.getLabel(),
				myData.getMedium().orElseGet(() -> Medium.DISK),
				myData.getFormat().orElseGet(() -> Format.VMDK),
				myData.getFilename().orElseGet(() -> null),
				myData.getSize().orElseGet(() -> 8096),
				myData.getDiffparent().orElseGet(() -> null),
				myData.getComment().orElseGet(() -> "autogenerated disk"),
				networkModel);
	}

	/**
	 * @return the medium
	 */
	public Medium getMedium() {
		return medium;
	}

	/**
	 * @param medium the medium to set
	 */
	public void setMedium(Medium medium) {
		this.medium = medium;
	}

	/**
	 * @return the format
	 */
	public Format getFormat() {
		return format;
	}

	/**
	 * @param format the format to set
	 */
	public void setFormat(Format format) {
		this.format = format;
	}

	/**
	 * @return the filename
	 */
	public String getFilename() {
		return FilenameUtils.normalize(filename.toString(), true);
	}
	
	public String getFilePath() {
		return FilenameUtils.normalize(filename.getParent().toString(), true);
	}

	/**
	 * @param filename the filename to set
	 */
	public void setFilename(File filename) {
		this.filename = filename;
	}

	/**
	 * @return the size
	 */
	public Integer getSize() {
		return size;
	}

	/**
	 * @param size the size to set
	 */
	public void setSize(Integer size) {
		this.size = size;
	}

	/**
	 * @return the diffParent
	 */
	public Optional<File> getDiffParent() {
		return Optional.ofNullable(diffParent);
	}

	/**
	 * @param diffParent the diffParent to set
	 */
	public void setDiffParent(File diffParent) {
		this.diffParent = diffParent;
	}

	/**
	 * @return the comment
	 */
	public Optional<String> getComment() {
		return Optional.ofNullable(comment);
	}

	/**
	 * @param comment the comment to set
	 */
	public void setComment(String comment) {
		this.comment = comment;
	}

	@Override
	public void init() throws AThornSecException {
		getData().getComment().ifPresent((comment) -> {
			this.setComment(comment);
		});
		
		getData().getDiffparent().ifPresent((diffParent) -> {
			this.setDiffParent(diffParent);
		});
		
		getData().getFilename().ifPresent((filename) -> {
			this.setFilename(filename);
		});
		
		getData().getFormat().ifPresent((format) -> {
			this.setFormat(format);
		});
		
		getData().getMedium().ifPresent((medium) -> {
			this.setMedium(medium);
		});
		
		getData().getSize().ifPresent((size) -> {
			this.setSize(size);
		});
	}
	
	@Override
	public DiskData getData() {
		return (DiskData) getData();
	}
}
