/*
 * This code is part of the ThornSec project.
 *
 * To learn more, please head to its GitHub repo: @privacyint
 *
 * Pull requests encouraged.
 */
package core.model.machine.configuration.disks;

import java.io.File;
import java.util.Optional;
import core.data.machine.configuration.DiskData;
import core.data.machine.configuration.DiskData.Format;
import core.exception.data.machine.configuration.disks.DiskModelException;
import core.exception.data.machine.configuration.disks.InvalidDiskFilenameException;
import core.exception.data.machine.configuration.disks.InvalidDiskSizeException;
import core.model.network.NetworkModel;

public class HardDiskModel extends ADiskModel {
	private Format format;
	private Integer size;
	private File diffParent;
	private String comment;

	public HardDiskModel(DiskData myData, NetworkModel networkModel) throws DiskModelException {
		super(myData, networkModel);

		setFormat(myData.getFormat().orElseGet(() -> null));
		setFilename(myData.getFilename().orElseGet(() -> null));
		setSize(myData.getSize().orElseGet(() -> null));
		setDiffParent(myData.getDiffparent().orElseGet(() -> null));
		setComment(myData.getComment().orElseGet(() -> null));
	}

	/**
	 * 
	 */
	public HardDiskModel(String label, Format format, File filename, Integer size, File diffParent, String comment) throws DiskModelException {
		super(null, null);

		setLabel(label);
		setFormat(format);
		setFilename(filename);
		setSize(size);
		setDiffParent(diffParent);
		setComment(comment);
	}
	

	public HardDiskModel(String label, File filename) throws InvalidDiskFilenameException {
		super(new DiskData(label), null);
		
		setFilename(filename);
		setComment("Autogenerated Disk");
	}

	/**
	 * @return the disk format
	 */
	public Format getFormat() {
		return format;
	}

	/**
	 * @param format the format to set. If `null`, defaults to VMDK
	 */
	public void setFormat(Format format) {
		if (null == format) {
			format = Format.VMDK;
		}

		this.format = format;
	}

	/**
	 * @return the size
	 */
	public Integer getSize() {
		return size;
	}

	/**
	 * @param size the disk's size
	 * @throws InvalidDiskSizeException if < 8192 (8GB)
	 */
	public void setSize(Integer size) throws InvalidDiskSizeException {
		if (null == size) {
			size = 20480;
		}

		if (size < 8192) {
			throw new InvalidDiskSizeException(size);
		}

		this.size = size;
	}

	/**
	 * @return the diffParent
	 */
	public Optional<File> getDiffParent() {
		return Optional.ofNullable(diffParent);
	}

	/**
	 * @param diffParent the diffParent to set
	 */
	public void setDiffParent(File diffParent) {
		//diffParent's allowed to be null.
		this.diffParent = diffParent;
	}

	/**
	 * @return the comment
	 */
	public Optional<String> getComment() {
		return Optional.ofNullable(comment);
	}

	/**
	 * @param comment the comment to set
	 */
	public void setComment(String comment) {
		//Comment's allowed to be null
		this.comment = comment;
	}
}
